export const memberList = [
  {
    id: 1,
    engName: 'Kaky',
    name: '강경모',
    position: '프론트엔드',
    mbti: 'ENFP',
    url: 'https://kaky.tistory.com/2',
    blog: '엉뚱한 한의사의 코딩 배우기',
    comment: '세상에 즐거운 일들이 너무 많고 내가 하고싶은 것도 너무 많아',
  },
  {
    id: 2,
    engName: 'Sgaeng',
    name: '강석영',
    position: '백엔드',
    mbti: 'INTP',
    url: 'https://kkangsg.tistory.com/',
    blog: '스갱이의 step by step',
    comment: `안녕하세오 개발하는 수학쓰앵님이에오 취미는 베이스기타에오 그럼 오늘도 햅삐하게 보내세오`,
  },
  {
    id: 3,
    engName: 'Cozy',
    name: '김민지',
    position: '백엔드',
    mbti: 'ISFP',
    url: 'my970524@gmail.com',
    email: 'my970524@gmail.com',
    comment: '외로운건 싫지만 혼자인건 너무 좋은, 조용히 눈에 띄고 싶은 모순 끝판왕',
  },
  {
    id: 4,
    engName: 'Nick',
    name: '김태호',
    position: '팀장, 프론트엔드',
    mbti: 'INTJ',
    url: 'cnt.taehokim@gmail.com',
    email: 'cnt.taehokim@gmail.com',
    comment: '문과생 간호사, 개발자가 되다! "융합형 인재"는 혹시... 나?',
  },
  {
    id: 5,
    engName: 'Mojito',
    name: '김효곤',
    position: '백엔드, 프론트엔드',
    mbti: 'ENFJ',
    url: 'https://mld42.tistory.com/',
    blog: '시원한 모히또 근데 라임 두 개나 곁들인',
    comment: 'Persistence and determination alone are all powerful -Ray Kroc-',
  },
  {
    id: 6,
    engName: 'June',
    name: '민경준',
    position: '백엔드, AI',
    mbti: 'ISFP',
    url: 'sprudwns33@naver.com',
    email: 'sprudwns33@naver.com',
    comment: '성공하는 사람이 되기 보다 가치있는 사람이 되자!',
  },
];
