version: '3'

services:
  backend:
    build:
      context: ./backend
    command: gunicorn config.wsgi --bind 0.0.0.0:8000 --timeout 180
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      args:
        API_URL: http://elice-kdt-2nd-team6.koreacentral.cloudapp.azure.com
    volumes:
      - build_folder:/frontend/build
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/frontend
    depends_on:
      - backend
      - frontend
volumes:
  build_folder: